name: React App
on: push
jobs:
    test:
        name: Test React App
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        name: Deploy React App
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Fetch code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying..."